blog/urls.py
from django.urls import path 
app_name = 'blog'
from blog.views import *

urlpatterns = [
    path("", HomeView.as_view(), name='home' ),
    path('signup', signup, name='signup'),
    path('login', login, name='login'),
    path('add', add, name='add'),
    path('logout', logout, name='logout'),
    path('delete<int:pk>', del_blog, name = 'delete'),
    path('activate/<uidb64>/<token>', enumerate, name='activate'),
]

emailCelery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blog.urls')),
    # path("google/", include('googleauthentication.urls')),
    path('accounts/', include('allauth.urls')),
     
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    blog = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='media/')
    add_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blog/forms.py
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.contrib.auth.models import User
from django.core import validators
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import *

def checkalpha(value):
    # if value.startswith("," | "!" | "." | "/" | "<" | ">" | "{"):
        # raise forms.ValidationError("This is invalid")
    if value.isalpha() == False:
        raise forms.ValidationError('This is Invalid.')

def checkuserame(value):
    if value.isalnum() == False:
        raise forms.ValidationError('Username should be alpha or digit only.!')
    # if value[1].isdigit() == True:
    #     raise forms.ValidationError("Username can't start start with dight!")


def checkemail(value):
    if User.objects.filter(email = value).exists():
        raise forms.ValidationError("This email is already taken try another")
# def validusername(value):
#     if User.objects.filter(username = value).exists:
#         raise forms.ValidationError("Username is inorrect")

class LoginForm(AuthenticationForm):
    username = forms.CharField(label = "Enter username:",
    error_messages={'request':"This field is required🤯"},
    widget=forms.TextInput(attrs={'class':'input'}))

    password = forms.CharField(label = "Enter Password:",
    error_messages={'request':"This field is required"},
     widget=forms.PasswordInput(attrs={'class':'input'}))
    fields = '__all__'
    labels = {'username':"Enter Username", 
    'password':'Enter Password'}
    
        

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label = 'Enter Password:',
     widget = forms.PasswordInput(attrs={'class':'input'}),
     error_messages= {'required':'This Password is required'})
    password2 = forms.CharField(label = 'Password Again', widget = forms.PasswordInput(attrs={'class':'input'}),
     error_messages= {'required':'This Password  is required'})
    first_name = forms.CharField(validators=[checkalpha],
    widget = forms.TextInput(attrs={'class':'input'}),
     error_messages= {'required':'First Name is required'})
    last_name = forms.CharField(validators=[checkalpha],
    widget = forms.TextInput(attrs={'class':'input'}),
    error_messages= {'required':'Last Name is required'})
    email = forms.CharField(validators=[checkemail],
    widget = forms.EmailInput(attrs={'class':'input'}),
    error_messages= {'required':'This Email is required'})
    username = forms.CharField(validators=[checkuserame],max_length=50,min_length=4,
    widget= forms.TextInput(attrs={'class':'input'}),
    error_messages={'required':'Username is required '})
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')
        labels = {
                'username':"Enter Username",
                ' first_name':"Enter F-Name",
                    'last_name':"Enter L-Name" ,
                    'email':"Enter Email"}
                    
        widgets = {'username':forms.TextInput(attrs= {'class':'myclass'}),
                    'first_name':forms.TextInput(attrs= {'class':'myclass'}),
                    'last_name':forms.TextInput(attrs= {'class':'myclass'}),
                    'email':forms.EmailInput(attrs= {'class':'myclass'})}


        # error_messages = {'username':{'required':'This username is Required'},
        #                 'first_name':{'required':'This field is Required'},
        #                 'last_name':{'required':'This field is Required'},
        #                 'email':{'required':'This field is Required'}}



 

class ChangePasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label= " Enter New Password :",
      widget= (forms.PasswordInput(attrs= {'class':'input'})),
      error_messages={'required':'This is required'})
    new_password2 = forms.CharField(label= " Enter New Again :",
     widget= (forms.PasswordInput(attrs= {'class':'input'})),
     error_messages={'required':'This is required'})
    fields = '__all__'


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'blog', 'add_by', 'image']

blog/views.py
# Create your views here.

from django.contrib import messages
from django.shortcuts import redirect, render
from django.views import View
from blog.models import *
from blog.forms import *
from django.contrib import auth
from datetime import datetime
from typing import Protocol
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from celery import shared_task
from django.core.mail import send_mail

# Create your views here.

class BaseView(View):
    views = {}

class HomeView(BaseView):
    def get(self,request):
        self.views['blogs'] = Blog.objects.all()
        return render(request, 'index.html', self.views)

# # class TodoView(BaseView):
#     login_required = True
#     def get(self, request):
#         self.views['date'] = datetime.now()
#         username = request.user.username
#         self.views['todos'] = Todo_List.objects.filter(username = username)
#         return render(request, 'todo.html', self.views)

#     def post(self,request):
#         username = request.user.username
#         user = request.user
#         todo = request.POST['todo']

#         if not todo:
#             messages.error(request, 'input field is required')
#             return redirect('list:todo')
#         if user is None:
#             messages.error(request, "You are not registered yet")
#             return redirect('list:signup')

#         list = Todo_List.objects.create(
#                 username = username,
#                 title = todo
#                 )
#         list.save()
#         messages.success(request, "New todo created successfully")
#         return redirect('list:todo')

   


def signup(request):
    if request.user.is_authenticated:
        return redirect('blog:home')
    else:
        if request.method == "POST":
            fm = SignupForm(request.POST)
            if fm.is_valid():
                fm.save()
                messages.success(request, "You are registered successfully")
                return redirect('blog:login')
        else:
            fm = SignupForm()
        return render(request, 'signup.html',{'form':fm})
        

    # return render(request, 'signup.html' {'form':fm})


def login(request):
    if request.user.is_authenticated:
        return redirect('blog:home')
    
    else:
        if request.method == "POST":
            # fm = AuthenticationForm()
            fm = AuthenticationForm(request = request ,data = request.POST)
            if fm.is_valid():
                username = fm.cleaned_data['username']
                pw = fm.cleaned_data['password']
                user = auth.authenticate(username = username, password = pw)
                if user is not None:
                    auth.login(request, user)
                    messages.success(request, "You are login successfully")
                    return redirect('blog:home')
        else:
                fm = AuthenticationForm()
        return render(request,'login.html', {'form':fm})

def profile(request):
    user = request.user
    if user.is_authenticated:
     return render(request, 'profile.html')
    else:
        return redirect('blog:home')




def logout(request):
    auth.logout(request)
    return redirect('blog:home')


@shared_task
def send_email(request,title, user, to_email):
    title = title
    mail_subject = f'{user} add a new blog'
    message = render_to_string("show-email.html", {
        'user': user.username,
        'title':title,
        'domain': get_current_site(request).domain,
        "protocol": 'https' if request.is_secure() else 'http'
    })
    send_mail(mail_subject, message, 'nepalisun22@gmail.com', to_email)
    # if email.send():
    #     messages.success(request, "Email has been send to users email")
    # else:
    #     messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')


from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

@login_required
@shared_task
def add(request):
    user_email = []
    email = User.objects.all()
    for e in email:
        user_email.append(e.email)
    print(user_email)
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            blog = form.cleaned_data['blog']
            add = form.cleaned_data['add_by']
            image = form.cleaned_data['image']
            obj = Blog.objects.create(title = title, blog = blog, add_by = add, image = image)
            obj.save()
            send_email(request,title, add, user_email)
            messages.success(request, "Blog added successfully")
            return redirect('blog:home')
    else:
        form = BlogForm()
    return render(request, "add_blog.html", {'form':form})


def del_blog(request, pk):
    id = pk
    blog = Blog.objects.get(pk = id)
    blog.delete()
    messages.success(request, "Blog Delete Sucessfully")
    return redirect('blog:home')

blog/templates/add_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  
<h1 style="color: blue; font-size: 2rem; font-weight: bolder;">Add Blog</h1>
{% if messages %}
{% for mess in messages %}
<h1 style="color:red; font-size:14px; font-weight: bold;">{{ mess }}</h1>
{% endfor %}
{% endif %}
<form class = "myform" action="" method="post" enctype= "multipart/form-data" novalidate> 
  {% csrf_token %}
	<fieldset>
    {{ form.non_field_errors }}
    {% for fm in form  %}
	  <label for="name">{{fm.label_tag}}</label>
	  {% comment %} <input type="text" id="name" name="user_name" class="input"> {% endcomment %}
    {{ fm }} <span class="error">{{fm.errors|striptags}}</span> <br> <br>
    {% endfor %}
<!-- 	  
	  <label for="mail">Email:</label><span></span>
	  <input type="email" id="mail" name="user_email" class="input">
	  
	  <label for="password">Password:</label><span></span>
	  <input type="password" id="password" name="user_password" class="input"> -->
	  
	
	  
	</fieldset>
	<button type="submit">Add</button>

  </form>

<style>
  *, *:before, *:after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    }
  
    body {
    font-family: 'Nunito', sans-serif;
    color: #040116;
    font-weight: bold;
    /* background-color:lightgray; */
    }
    
    .myform { 
    width:40%;
    height: auto;
    margin: 0px auto;
    margin-bottom: 10px; 
    padding: 10px 20px;
    background: lightcyan;
    box-shadow: 10px -10px -10px #CCC;
    border: 1px solid rgb(174, 18, 18) ;
    border-radius: 50px;
     }
    
    h1 {
    text-align: center;
    }


   .input {
    background: rgba(195, 174, 174, 0.1);
    border: 1px solid black;
    border-radius: 15px;
    /* margin:55px; */
    margin-top: 2px;
    margin-bottom: 2px;
    font-size: 16px;
    height: auto;
    margin: 0;
    outline: 0;
    padding: 5px 10px;
    width: 100%;
    background-color: #eef2f3;
    color: black;
    box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
    /* margin-bottom: 1px; */
    
    }
    
    input[type="radio"],
    input[type="checkbox"] {
    margin: 0 4px 4px 0;
    }
    
    select {
    padding: 6px;
    height: 32px;
    border-radius: 2px;
    }
    
    button {
    padding: 12px;
    color: #FFF;
    background-color: #4bc970;
    font-size: 18px;
    text-align: center;
    font-style: normal;
    border-radius: 5px;
    width: 100%;
    border: 1px solid #3ac162;
    border-width: 1px 1px 3px;
    box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
    margin-top: 5px;
    }
    
    fieldset {
    /* margin-bottom: 30px; */
    border: none;
    } 
    
    legend {
    font-size: 1.4em;
    margin-bottom: 10px;
    }
    
    label {
    display: inline;
    margin-bottom: 5px;
    font-size: 1.05em;
    color: blue;
    }
    
    label.light {
    font-weight: 300;
    display: inline;
    }
    
    .number {
    background-color: #5fcf80;
    color: #fff;
    height: 20px;
    width: 20px;
    display: inline-block;
    font-size: 0.5em;
    margin-right: 4px;
    line-height: 20px;
    text-align: center;
    text-shadow: 0 1px 0 rgba(255,255,255,0.2);
    border-radius: 100%;
    }
    
    @media screen and (min-width: 480px) {
    
    .myform {
      max-width: 480px;
    }
    
    }
    @media screen and (min-width: 980px) {
    
    .myform {
      max-width: 50%;
    }
    
    }
  
    .error{
      color: red;
      font-size:12px;
      font-style: italic;
      display: inline;
      margin-left: 10px;
      padding-bottom: 3px;

      
    }
</style>
{% endblock content %}

blog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com"> -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todos Pip</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <!-- <h1>Hello, world!</h1> -->

    <!-- navbar section start from here -->
    <nav class="navbar navbar-expand-lg bg-secondary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}"><h4 style="color: white;">Home</h4></a>
              </li>
          
            </ul>
            
          </div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"><h4 style="color: white;"> Hello , {{request.user.first_name}}</h4></a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:login' %}"><h4 style="color: white;">Login</h4></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:signup' %}"><h4 style="color: white;">Signup</h4></a>
              </li>
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link active" aria-current="page" href="{% url 'blog:logout' %}"><h4 style="color: white;">Logout</h4></a>
                {% endif %}
              </li>
          </div>
        </div>
      </nav>
    <!-- navbar end -->

{% block content %}



{% endblock content %}



    <!-- footer start -->
    <div class="footer-sm12">
        <p>© 2022 Nepalisun.All Rights Reserved</p>
      </div>
      
          <!-- footer end -->
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        </body>
      </html>
      

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %}
{% for mess in messages %}
<h1 style="color:red; font-size:14px; font-weight: bold;">{{ mess }}</h1>
{% endfor %}
{% endif %}
    <!-- todo list start -->




<!-- todo display list start from here  -->
{% if request.user.is_authenticated %}
<button style = "float:right; position:relative; right:200px; margin:15px 10px; display:block; padding:8px 12px; background-color:green; font-size:1.1em; color:white;"><a style = "text-decoration: none; color:white;" href = "{% url 'blog:add' %}"> Add Blog </a></button>
{% endif %}
<div class="todo-display-sm-12" style = "display:flex;">
  {% for b in blogs %}
    <div class="card mx-2" style="width: 18rem;">
      {% if b.image %}
        <img class="card-img-top" src="{{b.image.url}}" alt="Card image cap">
        {% else %}
        <img class="card-img-top" src="{% static 'img/test.jpg' %}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{b.title}}</h5>
          <p class="card-text">{{b.blog}}</p>
          <a href="#" class="btn btn-primary"> Added By : {{b.add_by}}</a>
          <a href="{% url 'blog:delete' b.pk %}" class="btn btn-danger"> Delete </a>
        </div>
      </div>
      {% endfor %}
        
      
        
    </div>
    <hr>
</div>
<!-- todo display list end  -->
</div>
    <!-- todo list end -->



    {% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% block content %}
        <!-- Login Start -->
        <h1>Sign In</h1>
{% if messages %}
{% for mess in messages %}
<h1 style="color:red; font-size:14px; font-weight: bold;">{{ mess }}</h1>
{% endfor %}
{% endif %}
<form class = "myform" method="POST" novalidate> 
  {% csrf_token %}
  {% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
<p style="color: red; font-size:0.7em">{{error}}</p>
  {% endfor %}
  {% endif %}
	<fieldset>
 
    {% for field in form  %}
	  <label for="name">{{ field.label_tag }}</label>
  <br>
    {{ field }} <span class="error">{{field.errors|striptags}}</span> <br>
    {% endfor %}
	  
	</fieldset>
	<button type="submit">Sign In</button>
	<button type="submit"><a href = "{% provider_login_url 'google' %}?next =/"> Login With Google </a></button>
    <p>Don't have account? <a href="/signup">register</a></p>
  </form>

<style>
  #id_username{
    width:100%;
    margin:3px;
    padding: 8px 15px;
    border:1px solid red;
    border-radius: 15px;
  }
  #id_password{
    width:100%;
    margin:2px;
    padding: 8px 15px ;
    border:1px solid red;
    border-radius:15px ;
  }
  *, *:before, *:after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    }
  
    body {
    font-family: 'Nunito', sans-serif;
    color: #040116;
    font-weight: bold;
    }
    
    .myform { 
    width:40%;
    height: auto;
    margin: 15px auto;
    margin-bottom: 20px;
    padding: 10px 25px;
    background: lightcyan;
    border: 1px solid red ;
    border-radius: 30px;
     }
    
    h1 {
    margin:2px;
    text-align: center;
    }
    
    button {
    margin:5px;
    padding: 12px;
    color: #FFF;
    background-color: #4bc970;
    font-size: 18px;
    text-align: center;
    font-style: normal;
    border-radius: 5px;
    width: 100%;
    border: 1px solid #3ac162;
    border-width: 1px 1px 3px;
    box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
    /* margin-bottom: 10px; */
    }
    
    fieldset {
    /* margin-bottom: 30px; */
    border: none;
    } 
    
    legend {
    font-size: 1.4em;
    margin-bottom: 10px;
    }
    
    label {
    display: inline;
    margin-bottom: 5px;
    font-size: 1.1em;
    }
    
    label.light {
    font-weight: 300;
    display: inline;
    }
    
    .number {
    background-color: #5fcf80;
    color: #fff;
    height: 20px;
    width: 20px;
    display: inline-block;
    font-size: 0.5em;
    margin-right: 4px;
    line-height: 20px;
    text-align: center;
    text-shadow: 0 1px 0 rgba(255,255,255,0.2);
    border-radius: 100%;
    }
  
    .error{
      color: red;
      font-size:13px;
      display: inline;
      margin-left: 10px;
      margin-bottom: 2px;
      font-style: italic;
      padding-bottom: 3px;

      
    }
</style>
        <!-- Login End -->
        
{% endblock content %}
        

blog/templates/show-email.html
{% load static %}
{% autoescape off %}
Hello User!
{{user}} Added New Blog "{{title}}" 
Go and check it out.
{{ protocol }}://{{ domain }}{% url 'blog:home' %}
{% endautoescape %}

blog/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  
<h1 style="color: blue; font-size: 2rem; font-weight: bolder;">Sign Up</h1>
{% if messages %}
{% for mess in messages %}
<h1 style="color:red; font-size:14px; font-weight: bold;">{{ mess }}</h1>
{% endfor %}
{% endif %}
<form class = "myform" action="" method="post" novalidate> 
  {% csrf_token %}
	<fieldset>
    {{ form.non_field_errors }}
    {% for fm in form  %}
	  <label for="name">{{fm.label_tag}}</label>
	  {% comment %} <input type="text" id="name" name="user_name" class="input"> {% endcomment %}
    {{ fm }} <span class="error">{{fm.errors|striptags}}</span> <br>
    {% endfor %}
<!-- 	  
	  <label for="mail">Email:</label><span></span>
	  <input type="email" id="mail" name="user_email" class="input">
	  
	  <label for="password">Password:</label><span></span>
	  <input type="password" id="password" name="user_password" class="input"> -->
	  
	
	  
	</fieldset>
	<button type="submit">Sign Up</button>
  <p style="margin-top: 8px;">Already have account? <a href="{% url 'blog:login' %}">Login</a></p>
  </form>

<style>
  *, *:before, *:after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    }
  
    body {
    font-family: 'Nunito', sans-serif;
    color: #040116;
    font-weight: bold;
    /* background-color:lightgray; */
    }
    
    .myform { 
    width:40%;
    height: auto;
    margin: 0px auto;
    margin-bottom: 10px; 
    padding: 10px 20px;
    background: lightcyan;
    box-shadow: 10px -10px -10px #CCC;
    border: 1px solid rgb(174, 18, 18) ;
    border-radius: 50px;
     }
    
    h1 {
    text-align: center;
    }


   .input {
    background: rgba(195, 174, 174, 0.1);
    border: 1px solid black;
    border-radius: 15px;
    /* margin:55px; */
    margin-top: 2px;
    margin-bottom: 2px;
    font-size: 16px;
    height: auto;
    margin: 0;
    outline: 0;
    padding: 5px 10px;
    width: 100%;
    background-color: #eef2f3;
    color: black;
    box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
    /* margin-bottom: 1px; */
    
    }
    
    input[type="radio"],
    input[type="checkbox"] {
    margin: 0 4px 4px 0;
    }
    
    select {
    padding: 6px;
    height: 32px;
    border-radius: 2px;
    }
    
    button {
    padding: 12px;
    color: #FFF;
    background-color: #4bc970;
    font-size: 18px;
    text-align: center;
    font-style: normal;
    border-radius: 5px;
    width: 100%;
    border: 1px solid #3ac162;
    border-width: 1px 1px 3px;
    box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
    margin-top: 5px;
    }
    
    fieldset {
    /* margin-bottom: 30px; */
    border: none;
    } 
    
    legend {
    font-size: 1.4em;
    margin-bottom: 10px;
    }
    
    label {
    display: inline;
    margin-bottom: 5px;
    font-size: 1.05em;
    color: blue;
    }
    
    label.light {
    font-weight: 300;
    display: inline;
    }
    
    .number {
    background-color: #5fcf80;
    color: #fff;
    height: 20px;
    width: 20px;
    display: inline-block;
    font-size: 0.5em;
    margin-right: 4px;
    line-height: 20px;
    text-align: center;
    text-shadow: 0 1px 0 rgba(255,255,255,0.2);
    border-radius: 100%;
    }
    
    @media screen and (min-width: 480px) {
    
    .myform {
      max-width: 480px;
    }
    
    }
    @media screen and (min-width: 980px) {
    
    .myform {
      max-width: 50%;
    }
    
    }
  
    .error{
      color: red;
      font-size:12px;
      font-style: italic;
      display: inline;
      margin-left: 10px;
      padding-bottom: 3px;

      
    }
</style>
{% endblock content %}